apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 923687682884.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
        ports:
        - containerPort: 80


